# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UQsKMciorf/vppX5SODTOIk1a8OeE5WmiUxyNRNfYwr5olrvJix+ZQ==,iv:XIT38WW+EUldwrHduEt6SrLxKgjuWNhHMjBHsK+RLDM=,tag:x4jRnOliFvNtXKe1IfWw4w==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcmFEK2FRczUxckoxQXhp
        WTE3Umw0cDFtWE1laXMvWThzWHNvK1RmbkhJCmpKS0w3eVR5Wnl1TlNjdmlzMUpB
        ZGRsbnNCQnlST1R0eE1xSEpwTHFNbTgKLS0tIHF4S0N2MHk2ZEY1QVlSZFdBcGhH
        VEd3bk5yWVJyMjNoVlR5ajBMQzhaUE0K/aT+ra1NVN1ksH3wEiabbQEmw7E9Fu65
        MyQDr8tS1RouUlWcSrdn6wQ7bO3jCbpYuLxWc2UElQMi9YZKrS2S3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T03:06:14Z"
  mac: ENC[AES256_GCM,data:yn5DVmCcvY7uhN4+q07D5LtUmEOVnBTUvfJv+NJswWq1oyrpP0UuFTAU0kYdIIDJ/Xk/Mtob8nVqDKpQ3ULyW8US1CXOjdPApIuGlRkyQ7zG88i64sIovd47/EhhSCEHXd5hK8jk3Xdy9vVq2ToQUIVcJ2AhXBqEbXY4wX+doL0=,iv:Z9z2DO6sloK/85gQb/OeCCVluLWg323Cu3Uq8DpWLV0=,tag:58SpHPF3MgBtSgFVvFaOYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
