# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:LH3vUwgUNuU/+ICDs2q01fuSwA/VPxG3hB016u4Isyo=,iv:xG5NFHufoXXwsYw4h+5mG9lqD4raICUPW6OtIlRDM+w=,tag:TLBrYCNU5nbBkjddyhzH+w==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWHFQQ1k0THRJSXlGeUdS
        aWlhYVM1OFhmSm8rTnlnOTlpR2lLaFhvWVZvCmxPK0d1NVJFOEFwQnhTbnBDdERL
        NTZ3Q2pVZUFCRTRZaEM2SytVbFlBcTAKLS0tIDR4bVdHYXRMdGI4OUc1cU5kb1Mr
        RytmdXNTN2J2WHNvM0c1V3lQSkFET1UKMlGeOup8qdSx8SuH18190UhQPARfagw9
        K4RQTanJzU66ObvtwUpjwHuvEnz+7N7UjQ5xjGPMToPeN5uj077+xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T11:34:00Z"
  mac: ENC[AES256_GCM,data:+vd/8R3DcZwh2fPSAqJJPJHIQObu5Gh+rGtO9BO8NiokgIrRu8X5ONXONciirsgV74JrMm+QeOabQ3Wm8FL9Jqvc5VcmLxxeN7jSx//5bmkWHEYlNGLvm0/r82fAWujvwE2Eks9J4LkKbeOj6kPnrZt+1VijA2ClsTR/sIvrEwM=,iv:3FjfBW4hmjteZH4+ZX3zHJtgObU7zrkFc1tCr3oM6Os=,tag:tf9y57GNr5l/WtWbcUqTdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
