# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:rzIx45/R73DtMhc/VNW7BhCSBHU4fcv2wqj2U1b2qVw=,iv:tqrhdimjfUZcOdROeU/r7JoMkMr1j1g/mBW31z4rlDU=,tag:Z+/WtYmIzyFex3DDzAVTAQ==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSmRCQndqcG9LUFliRWJl
        VEdQdWl6Wm44YnBxbzFwZHp2TnBHS3RtYWtrCit2SEpWUFdRbkxKdDdkd0VLWGs5
        YnhZK3QwaWtpd21QbUhvNG1ibVJHcU0KLS0tIE9sazFOMFM4TVM0UzZoSld6NkNn
        bmlpU1hic2NsNmxBOERDWlNGTmNENEUK2YQVsSElMRQ5RIJOaujPqtRFXZecZHnO
        9RzTXc8ZAPvslQW5LqT1lm2X2VXiHl4p2l8XzIs3CkVcLxoY4l4G1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T04:16:14Z"
  mac: ENC[AES256_GCM,data:apCi/b7v5i8DG4l7Ic4p/dGVF0JwR5YRNG1tZYDLkArUk59v7lpLyPgP8pizaNro0fNP5K5RjyGiDGVh62p4+om18juMDa91fPFDmSoLJJQ5UDXWFjmCLvEINZ3/WGsVqxbjDVYjyRb9U+Nm8Mp4+Be4ugu7c3l7KJ9pDRxkrcI=,iv:PuvsqN0JJIGrsCKPK1wMgnY/7xqBbT1+ZNfNIkIdQW0=,tag:JhjjK1d8HFDToFQZspVsDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
