# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:uibIdX1/1lI870RYtIC5D8x+hrAd+L8Jgg33rXDaTD3s5o9YZkGEcEUNQamLxrOKnCzPZMLVW8C35Ddk6104QXnPtrjaIkXDiT9fyFvOq1gFJC4Jt268qZjG/nwzLFSHmzX9520Sn2SlVrF5iBpRJKP+v5Uko52Ka9xqQrdXe5MagWQ6DzVhZUadB2i3//aAvM5JjEPHiBBowrNW96xkBQFirUp2xy6mQOuabRSxHekxPEWz,iv:ub5VcLHfP3wCl10lhwxlkaIahUXeFon3AnOgDef06ls=,tag:XtyrErx38Es1qwHwpj35Bw==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYzlmZFRtWUJ0cDJZZkZh
        NENqRW1VcFlYb3NrVENHZ2Z0NkloUUNNN3hjCmxGYnBJbzRqRGVsdUVjUVVHM1lk
        RG9kWVNZdTBURXI5VWZ0SksvVkNPbEUKLS0tIG9PREdGMUpzMmRUckZ6SklwWHN4
        OVBWNGZhSHZYQk0zMGRYL3RBWGMxOWsKq604mDfTzgLWUftPeI6AXGldItW4Q7W8
        M05hbs1nbAWNptINepEYwVuRYJ5gUrD+kX2vnx8CsSZVOGOds++Glw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T04:09:14Z"
  mac: ENC[AES256_GCM,data:LRNtKHNK1PGItl/eDtLOx4c34mAlSOi5+sgf9UKnyJH7+1AFSqfI4ZynV3o3eLj6+nsmbAuQ/DAOsztxtGm8Jd+rnAK6wfjoEys/KKuvj6JX1f2as6dpYxhZ+gDZCl7qFqsIfBVYkxgrZeD8W8yP8Qes5np1NjkLksOkT2UmLqo=,iv:kVoL2yjYZPa5lJL9nxeG8ZZCkvB6OpMeXx8gFhsKXvY=,tag:e6yvT1Pt2Z1QJMKldqJLAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
