# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:++AelKrM7u/olyc576HmpnxrQdPmDc4FEsIaAPm2Fbt1UG9f72uQnTWQ5W/DQHOu/k/jVbqOhc+z5v6ZLAMnPdm8HNoXt4L9OLva/htBiIyHigOcxhHsOx0oDw3OvCCgbwiSGoYJGaQ8DbGYI3RASAJhgMQXFUkzWq61fni+rYl1/Rqdqgk2sOOmOUxdXaHtRWIPOp9UqKqWvS0W4L2ZzY+PQmnNaZa3TVptE3olOPSNbLpo,iv:CFJ78j6180UEu6VbpqIk3R2pUt57UTh6ZGp1A2tGG6E=,tag:1tpItT0PtIC652iQYPjt9A==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNlA1K3NMWkczTDIrcVVx
        b0d1NUptV2RBN05PVkZSbFpxNHFIeTc0ZVJrCjVXQU51aHVjMy9SMXVFYlpWbjR3
        UjU5Tk8vQll2NURidVFHem1tTC9ZSU0KLS0tIDgyRXBYK3FGZlFPZEpBK0lqS1hl
        UjJKN3NDV2p1THdka1B1ajNJZjRTTWsK49/RNJZU3ZMqgr/G93orbagWclZ5GAS4
        S6sOcoNrzd9SRK2syfG7oavY5VTDhP4Kuj+BowhsZyGxh8Ovb/q6vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T07:26:52Z"
  mac: ENC[AES256_GCM,data:Sj9W2Rm2rttoxrcslYNmsuEtWR8mclcIHYJJ3N9degPKkYIv4DQZ8Z4VSYyYlpRe1eZOP3FgHP0d0iP7V+NHYzusXzmML0FHPRY8A+SD40DQij/XejIqbHbewxZcEfJiXRCvSJyOtTfUpI54fXT2qh5tudycT22xKj1nv4XlYbE=,iv:plb9kbuNkipCNforgoReQyAAC+Kuzm1u+y5XVNZZySQ=,tag:CBRscjqXPYlekJu54FblzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
