# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:d71I6Q9s4CwHivbd77so3xVszP+kIjBbgVzP3uB/xOw23C7kOPxvgA==,iv:BckGaMXhEOQ2FK8E7OoeenYqH7ytQtGVdCwlETTrPvI=,tag:BSLxUoSqOLM3sayOO6/vFw==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeGhzcWZ0Z3lvYmdBSU1N
        TzlKbjZTNHBiZk00dVFFa0NaR09aMVA5dUFBCmZ6cU01eHhPZ25Kd2JKNUF5Q3U1
        R1VUZ2xwUTlneG8rQ0s2YlNmYStscW8KLS0tIE9BVFMzNHJ4UWI3aEs3SlBodFJT
        OURZbW1rNE9QUGVrNGFyT01PdlBBR0EKwWOA8uVFdQfwQOz9201g03vh2FoXTNjE
        WIXTR7jHpN3MogEGi/poTiK4u2z1fALuKI65xQjYE0OfaqnOZkotKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T03:06:14Z"
  mac: ENC[AES256_GCM,data:ybP9MoqPO/Oa3Ll1Z5kD03Bfuk9PGv1lv/zFu5Wa+HpYf7Yi7eztyRO2raWbcoaJ4wusIRmBFtT63kvucnu2V7W+FdV6osuhi2zu0JpVyQiaHkSS8gvZIrT9ZpuK4yKXugvwMvyhX+49PxXojtlQ0+1rSAQrBIOVJ9Sc+mOU+aY=,iv:2giMmlnGhZ09322a2v1S22vr0dvJ2TvCSLTaW+woPr8=,tag:aHgH1fSQ7WgAQxH2mhX66g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
