# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:VBAQ04r1Rr9CFnT8iILpWUus2tRnJZYQSLQFd5NAeo0a4wz6ZmSD7Q==,iv:3hPtlIZdsuOwYT4Rt6nAf3XoYXsU8XwUOgYYW0ivAWo=,tag:2GlwW7SDxaQ8VZfeTM/sCg==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb3krb0paVGg5V01ncU43
        alh5UmJrU1dYR1NhcHFQL1Z1N2w1OXpxaldFCm9mVjNwcFlJeHVya0Vud0d1TnIx
        ZmdnN3psSmw5V1orUHlBRUZXMVhSNDAKLS0tIFB5dGZkUlVVQXQ2ODgxOVlwYkJN
        MnJ2Rm9LR2t3Q3YzemFvREJOd2Z4emsKD+8oMjt9aZgpl3WIz6j9oYYIXFEpBeU/
        exUBJS9u66RF9nHyY4uiRPJ8L34jEG27vde9ZGw/vnHSV4rP0xLUmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T11:58:47Z"
  mac: ENC[AES256_GCM,data:gObWTKkvd/GLuLmN43Am7kP0WPzDwFGL0lKttfzLXtYTgQ7gGBmU/IXKdrwYZnV36SlAqaVKaZb9ZenbXbaFGwtJei2uAt8nnGt3ArlqQ17zbkzOJvpdiVB1nI/Dx5aJTp1L4eo+ExxXFPybBlmZXaHcUNm7WHcU8gIw2sypUAg=,iv:2Ujfw1/E8k9mYqiOFnx9NFreGk2cjV1T5PPxGK0l/74=,tag:5oVAxHeAGxgy8Yzb/ji2Aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
