# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.130.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.10.130.100"
  - "k8s.vierra.host"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "cp01"
    ipAddress: "10.10.130.101"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:01:01'}, 'dhcp': False, 'addresses': ['10.10.130.101/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}], 'vip': {'ip': '10.10.130.100'}}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0a:01'}, 'dhcp': False, 'addresses': ['10.10.140.101/24'], 'mtu': 9000}]

  - hostname: "cp02"
    ipAddress: "10.10.130.102"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:01:02'}, 'dhcp': False, 'addresses': ['10.10.130.102/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}], 'vip': {'ip': '10.10.130.100'}}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0a:02'}, 'dhcp': False, 'addresses': ['10.10.140.102/24'], 'mtu': 9000}]

  - hostname: "cp03"
    ipAddress: "10.10.130.103"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:01:03'}, 'dhcp': False, 'addresses': ['10.10.130.103/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}], 'vip': {'ip': '10.10.130.100'}}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0a:03'}, 'dhcp': False, 'addresses': ['10.10.140.103/24'], 'mtu': 9000}]

  - hostname: "worker01"
    ipAddress: "10.10.130.111"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: false
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:02:01'}, 'dhcp': False, 'addresses': ['10.10.130.111/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}]}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0b:01'}, 'dhcp': False, 'addresses': ['10.10.140.111/24'], 'mtu': 9000}]

  - hostname: "worker02"
    ipAddress: "10.10.130.112"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: false
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:02:02'}, 'dhcp': False, 'addresses': ['10.10.130.112/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}]}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0b:02'}, 'dhcp': False, 'addresses': ['10.10.140.112/24'], 'mtu': 9000}]

  - hostname: "worker03"
    ipAddress: "10.10.130.113"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: false
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:02:03'}, 'dhcp': False, 'addresses': ['10.10.130.113/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}]}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0b:03'}, 'dhcp': False, 'addresses': ['10.10.140.113/24'], 'mtu': 9000}]

  - hostname: "worker04"
    ipAddress: "10.10.130.114"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/nocloud-installer-secureboot/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: false
    networkInterfaces:
      [{'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:02:04'}, 'dhcp': False, 'addresses': ['10.10.130.114/24'], 'routes': [{'network': '0.0.0.0/0', 'gateway': '10.10.130.1'}]}, {'deviceSelector': {'driver': 'virtio_net', 'hardwareAddr': 'bc:24:11:bc:0b:04'}, 'dhcp': False, 'addresses': ['10.10.140.114/24'], 'mtu': 9000}]


# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-registries.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

