apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:f7niIIwWrvKT0NTlAw==,iv:h77gWVZOuNDjw2Ql+1wMe+0qUI6V6j9ZMJDG/OTlE6U=,tag:nUXeZpcYHuxb8ZZVTHxFAg==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQTVXbDFKbGlrZ0Y2L2cw
        U1M2eHdRUDdyUExUWnVVNnczRTR2dEJRRVU0CnQwVzdMOUNjd012a3EyaHE0SHpN
        QlkydUZjaytRcnBBNHE3bGs5RUROZkkKLS0tIGxRYS9QUzZqNmdZZTk4NGFrckRp
        UTlUaENDVmZxSmE3ajJJSzN1aW81cVkKWH/7Obm1aLGK/RxszsIIafU+huyP/ufC
        Y1mcXNshif3vM3kvIaRjWCj4NGCIDLYpgKoAe8SDE+xizF0BnUY5yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T04:16:14Z"
  mac: ENC[AES256_GCM,data:FRxdFi3BT0oXLqAHAVacwJ4fJ1dOQlIAnIAUdywJNdBskugwAxrJseKV71fJHFAxxdpKvq55/wMdb8idjbE7puI8xMKcxnZp6/6Do7MDA61rIfyATndWVvPT+IOC1hm74CU6m5Vg7wieVeVU9tp/indAUpIiWAe15QYCFsylfh4=,iv:5FXMwQ+4G3zJE3aqob7O9eDvUpiwR57Zs8fpP6yoUQs=,tag:RRoFcvCXl/LN7WIwEbhzHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
