apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6MokN2NmcRtgdVVGIQ==,iv:xExFebTlz9rmOV+2aGxtUlcJqe8F8XKjdMWXfzjLsuI=,tag:54Rj6cS7jx+YdPCUXhizGA==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSTV4bXA2VkFJK0cwTXps
        TWZHdVBlZjNlOVBvM2tyRG9XSUxSdDV6WG1FCmU1dEZidGd1dGxTS1paU0dEREk3
        K0hVdS9QazFVTHc0YmQ5QXJkSFVOM0EKLS0tIGs3eUFWUkQrM0lrc0pNcW1nbXNn
        RVdiNVF1RFZweWFaeDlJWkRJYTl0ME0Ks2DJIOBJaoiwMQ+cJ8COHOC9UkVeggak
        yo8yuUocMgs0qS8He/QMlvw8xG+vSC96mActhphBvxJGi9BksD/yBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T04:09:14Z"
  mac: ENC[AES256_GCM,data:Bv34gb2oRW83nv6biVRjX3OW2vc9BiMocyH2T29dci9S5u5TeaiVZzrMINXvIjh7ILFEP4iceEbZznlDcXbbzPggmUZL7kqhQ1cWZFioOT/YZ8ML37zzh8E63QDlA8o2QvEyKYYAZORhVXHYVxWfWfvPGUWjlD2jGUWRugPEcvw=,iv:limMNPgEOe2Xrs0n4/tQe8CYDz5YlX+XuT7gf4o/c88=,tag:NwaCVkzS3GNreX+R56ujpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
