apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bNaCCssJ0epeH88=,iv:dc/lM3zQNt4zuLjMyBYxtdwAwxWg+fAUzx4dtp4gICA=,tag:eKOKL+yHB+P8gaxydJN26A==,type:str]
sops:
  age:
    - recipient: age1ac6hekwhff2hhdfv5pp96tjnycy2wjshvhsfmpch8nlqj2qv9dqsr3ducp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZmptTlJpMmErWGYxd0J0
        WmhyOWF1REdydWZPVFlsQW9OZGRCMzRHN2xJClgvZGl5bmk0dUs4VEZCTlduTmZ6
        SWJYSUdlM0xuL05EQUk1S0lvcW1wK0UKLS0tIFFBaGVVS3pNNkx6YVZiTk9pL0NM
        OVVrTk93TS9JaUJ5WC9mOCtHcjNPNEkKgvs6UcBAK08OITigxVLF+yx5OBXdulhB
        Ww3iie87scPvpa5QcH3cgAcaU+FmuPhP4QKLUIcQXwxt6+9nPRnFGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-01T03:06:14Z"
  mac: ENC[AES256_GCM,data:psKq+cggpW3kh/vbCqiaD1Chf+m7hljEkhlQNaa+NZMHbpRddvE4m1/vduwGOBuTs5UUps7SzPWcPsGEXWYbNymUK4CLeg9+GI7ZLVOhELQMFLAyDxVIZKSdkmKw20nsw2AWl9BP1oszhi5CZTANh3dMJrsOV5T6yFqElcI7row=,iv:SJenskBQ9n9JF3JaGMswqH2JD1JLXxRpxJWsagBoaiI=,tag:GKI2ZUDcGK6tT8YjMYyBsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
